logging:
  level:
    de.oglimmer: info
    de.oglimmer.kinesis.ReqRespVerifier: info
    de.oglimmer.kinesis.DataReceiver: debug

shardsToRead: 0
dataGenerationSpeed: 1
waitTimeInBetweenRead: 1000
payloadSize: 4000
dataGenerationThread: 5
asyncSenderThread: 5
